config.ini, src/config_loader.py, src/output_manager.py, src/setup.py
-alternative endpoint specified in config.ini
-alternative endpoint must be compatible with openai's streaming chat completion API
-finding and configuring services for alternative endpoints are the responsibility of the end user
=> Allow mantella to use alternative openai API-compatible endpoints

config.ini, src/chat_response.py, src/output_manager.py, src/setup.py
-provide options to support openrouter.ai API by entering its api base as the "alternative_openai_api_base" and its model terminology as the model
-prevent tiktoken from erroring out by setting it to gpt-3.5-turbo if it doesn't recognize the llm model so that config.ini can be simple and just use one field for the model regardless of whether using openrouter or openai.
-add headers to api calls that are required by openrouter; these do not seem to interfere with calls to openai or textgenwebui in testing so seem to be ok to leave in for all API calls without using conditionals [note: perhaps this would be a problem if other services use different headers but I'm not aware of anything else doing this right now, and prefer as much simplicity as possible in the config.ini to reduce …
=> support openrouter.ai API

src/setup.py
-When using custom model, if unrecognized, code presently sets token_limit to custom_token_count, however custom_token_count comes from the config.ini so is cast by default as a string, resulting in an erorr when token_limit is then compared to 4096; at that point token_limit is a string "4096" so cannot be compared to 4096 an integer.
-This fixes that error by casting the string as an int, and if there is an error, throwing an error and setting the token_limit to 4096 by default.
-Also adds llama-7b-chat as a recognized model as well (not just 13 and 70b)
=> Update setup.py to fix int / string error

src/output_manager.py
Sometimes local models like to give responses contained in double asterisks. These are now handled by the output_manager filters
=> Replaced cases of double asterisks with single asterisks

src/output_manager.py
Changed modded NPCs message from "Modded NPC" to "Unknown NPC" in case it is just an NPC Mantella has not encountered before. Added wav and lip files to newly created voice folders in order for Skyrim to recognise them.
=> Modded NPCs messaging fixes

config.ini, src/chat_response.py, src/output_manager.py
-add stop=['#'] parameter in output_manager to call to openai API to stop models from repeating a ###Instruction: format in their responses sometimes used by non-GPT models using a framework that utilizes the openai API .  Once this character is generated the model will stop generating and then because it will be too short to be its own sentence, mantella's other cleanup code naturally deletes it.
-Adding max_tokens=300 in chat response as an openai parameter to allow the summary enough tokens to summarize but without eating too many tokens.  This also helps with koboldcpp where the default max tokens length is 80, which is nice to keep responses pithy but not long enough for full summaries sometimes.
-add line to config.ini to provide an example of the IP address to use for koboldcpp …
=> misc non-breaking changes to support future koboldcpp openai API support

README.md
I for one have a single SSD drive. So I am noting the strange behavior of Steam when trying to create another Steam Game Library on the same drive and how to get around that.
=> README.md: Steam Library besides another, note

config.ini, src/config_loader.py, src/output_manager.py
-based on user requests, expose standard openai parameters for experimentation
-do not use parameters for chat response since that is a single-shot and things like temperature changes or length could have a negative impact for summaries
-expose temperature, top_p, frequency_penalty, max_tokens, and stop parameters, and set them all to the openai defaults except for max_tokens since default max tokens for openai is infinite.  250 should be a sufficient balance in combination with max_sentences.
-as per openai api docs, stop can be a single string or list of strings.  Tested with both.
-tested with koboldcpp (via google colab), openrouter and openai and had no errors.
-may want to add to the readme that if these are set to parameters openai does not expect chatgpt errors could occur at …
=> add customizable openai API llm parameters

config.ini, src/config_loader.py, src/stt.py
-Credit to Elbios from Herika discord for a ton of help on this.
-This commit allows advanced users to run a whispercpp server and query that instead of using faster_whisper if they want
-Main benefits are reduced VRAM requirements depending on model, greater control of server parameters, use of distil_whisper model and benefits of any further improvments to whispercpp
-Still default to faster_whisper as "hands off" method for whisper for other uses.
-In theory this PR could be expanded to add the headers and model field ("model":"whisper-1") necessary for openai's online whisper by importing openai, using authentication through openai.api_key, but for some reason when I tried to add those, the whispercpp server would not work so leaving out for now.
-Another benefit is that when herika …
=> support whispercpp server as alternative to faster-whisper

config.ini, main.py, src/game_manager.py, src/output_manager.py, src/stt.py
Streamlined the Mantella spell conversation loop by:
1. Merging the Listening... / Thinking... / Error statuses into one file (`_mantella_status.txt`)
2. Passing subtitle data as part of the `_mantella_say_line.txt` check to avoid the redundancy of having both a `_mantella_say_line.txt` and `_mantella_subtitle.txt`
=> Mantella spell text files refactoring

config.ini, main.py, src/character_manager.py, src/config_loader.py, src/game_manager.py, src/output_manager.py, src/setup.py, src/stt.py
Added handling of radiant dialogue (conversations which don't include the player):
1. Edited multi_npc_prompt to consider whether the player is in the conversation (multi NPC) or not (radiant)
2. Added conditions to `main.py` to consider the radiant dialogue format
3. Added ability for player to "interrupt" radiant dialogue (ie stop streaming LLM response) and join the conversation
4. If radiant dialogue, player response is changed with radiant dialogue stage directions
5. Fixed bug with hotkey still being searched for despite its removal from config.ini
6. Added warning if model failed to load that `alternative_openai_api_base` may need to be changed in config.ini
=> mercury7 radiant dialogue and multi NPC merge

README.md
Sorry, I've had enough of the old tutorial video and propose to remove the whole section. JackTheFallout had deleted all project files related to that video and will not update it.
The instruction to click on 80 web links for voice models is the worst part. Manual creation of unnecessary folders... and so on.
=> README.md: Video Walkthrough section removal

.gitignore, src/output_manager.py
I changed the way output_manager.py handle the content it get from the LLM.
So it stop at the first "." , "!", "?" , ":"  and the content behind these marker is stored for the next content batch.
=> Change to output_manager.py to stop cutting mid sentences

src/game_manager.py, src/output_manager.py
- Corrected the NPC who says the final goodbye keyword to the active NPC.
- LLMs are now allowed to switch NPC by giving just their first name
=> Character switching corrections

src/game_manager.py
- set to be always 'false', as radiant conversations can never reload
=> Fix to reload_conversation failing

src/output_manager.py
Some LLMs have some seemingly random token streaming formats. Most LLMs stream in a way where an action ("NPC1:" / "Follow:" "Offended:" etc) are neatly streamed as one token, meaning the colon is always the last character. Now colons are searched anywhere in a token to accommodate these alternative LLMs
=> Check for action colon within any part of sentence

src/config_loader.py
Added check to see if Skyrim is installed in Program Files, and if so, asks the player to confirm the warnings. Some players are able to get Mantella working with Skyrim in Program Files, so the confirmation message only appears if `_mantella_skyrim_folder.txt` is not found
=> More verbose skyrim install checks

README.md
Removed instructions for adding xVASynth Elder Scrolls dictionary as it does not work on v3.0 of xVASynth. Trained v3 Skyrim models already have some comprehension of Elder Scrolls terms unlike v2 models. Will re-add once the dictionary works again. There is a workaround that includes replacing the cmudict.txt.
[xVASynth issue](https://github.com/DanRuta/xVA-Synth/issues/62)
Added optional instructions for installing the xVASynth DeepMoji plugin. I don't think I can wait on DanRuta to merge the PRs, so v0.9 of the plugin will just have to do. v0.9 of the plugin replaces base xVASynth files. It will remain v0.9 until xVASynth is updated.
=> README.md: removed xVA dictionary; xVASynth DeepMoji plugin

config.ini, src/config_loader.py, src/llm/openai_client.py
Reimagined version of `alternative_openai_api_base` (now `llm_api`) which simplifies the LLM service connection process:
- `auto` setting: Mantella now auto-resolves the LLM service to connect to. The order is: check if Kobold is running -> check if textgenwebui is running -> check if `model` setting in config.ini has a slash in it's name (if it does, it is an OpenRouter model, if not, OpenAI)
- Named services: Players now only have to set the name of the service they would like to connect to ("OpenAI", "Kobold" etc), removing the need to copy paste long scary URLs
Solves https://github.com/art-from-the-machine/Mantella/issues/145
=> LLM service auto resolver

src/conversation/context.py, src/conversation/conversation.py, src/remember/remembering.py, src/remember/summaries.py
Conversation reloads are triggered when a conversation gets too long. A bug in the code caused the length of NPC summaries to not be evaluated if a reload is needed early in the conversation. 
Summaries are not created for conversations that are too short (design choice), yet if the token count goes over a given LLM's limit and a summary cannot be created, then an endless loop occurs where the conversation is constantly at the limit and cannot be shortened. This PR fixes this problem by allowing an extra check to see if the length of previous summaries is too long, and if so, shorten them.
=> Added context to save_conversation so that reloads force a summary length check

main.py, src/conversation/context.py, src/conversation/conversation.py
Token limit calculations have been repainted in a couple of ways:
- `token_limit_percent` has been renamed in main.py and context.py to `starting_prompt_token_limit_percent` to better reflect what the percentage is calculated against. This percentage has been bumped from 45% to 50%. ie at most, the starting prompt (including the NPC bio and long term memories) can account for up to 50% of a conversation's token limit
- `reload_conversation()` in conversation.py is no longer triggered by percentage calculations. Instead, it is triggered when the conversation so far (including the starting prompt, NPC bio, and long term memories) + `max_response_tokens` + 250 tokens exceeds the given LLM's token limit. `max_response_tokens` is added because the calculation needs to predict whether the next …
=> Redefined how token limits are calculated

main.py, src/stt.py
This PR resolves an issue where Mantella hangs when waiting for text input when the player has already ended the conversation.
Instead of calling `GameStateManager.load_data_when_available`, `Transcriber` has a new function `_get_text_input` that polls both `_mantella_text_input.txt` and `_mantella_end_conversation.txt` to ensure that it doesn't end up in an endless loop.
I also fixed an instance where `_mantella_end_conversation.txt` was being checked for the value `true` without first converting it to lower case.
I've only tested this fix with Skyrim and Skyrim VR but not with Fallout 4 or Fallout 4 VR.
Fixes #241
=> fix: check end_conversation.txt when waiting for text input

main.py, src/game_manager.py, src/output_manager.py, src/tts.py
NPC voice models are now loaded at the time of the character being loaded, rather than when they first speak. This allows Mantella to change the NPC's voice model to a generic one if the specified model isn't found.
If no voice models can be loaded, a more helpful error message displays to say as much, rather than giving a generic LLM API error.
=> Better voice model loading

src/game_manager.py
Background:
I've been tinkering to solve this issue that some users are having where the getdisplayname() function fails to run in Fallout 4 leading to the game not loading NPC profiles correctly. That prompted me to look into why the ID search in the Mantella Software lookup functions weren't picking up the slack when the name is missing. 
Changes:
Modified the hex conversion of character_id to trim the first two characters instead of replacing X with '' Modified the find_character_info to make it so partial matches are checked for 5, 4 and 3 characters sequentially and leading zeroes are ignored in both the converted hex value from the game and the hex value in the baseID in the character.csv. There's also a few check in there to account for float & NaN values
=> Fix find_character_info

src/games/fallout4.py, src/games/gameable.py, src/games/skyrim.py, src/setup.py, src/tts/ttsable.py, src/tts/xtts.py, src/tts/xvasynth.py, src/utils.py
Data generated by Mantella.exe (voicelines, conversations, logs, config.in) now gets saved to Documents/My Games. This allows for various installations of Mantella in different locations to all use the same data.
=> Change save data folder to my games

src/config/config_loader.py, src/llm/openai_client.py, src/setup.py, src/stt.py
As well as checking the folder the exe is running in, check if a secret key has been saved to a `GPT_SECRET_KEY.txt` file in the Mantella mod's parent folder.
When Mantella.exe is run via `Mantella/SKSE/Plugins/MantellaLauncher.dll`, the exe's directory is `Mantella/SKSE/Plugins/MantellaSoftware/Mantella.exe`. To save the player from having to click though a bunch of folders to get to `Mantella/SKSE/Plugins/MantellaSoftware/GPT_SECRET_KEY.txt`, the secret key is instead stored in `Mantella/GPT_SECRET_KEY.txt`.
=> Search for secret key in mod parent folder

src/character_manager.py, src/characters_manager.py, src/conversation/context.py
Fixed changes in the transient states of an NPC (`is_in_combat`, `is_enemy`, `relationship_rank`, `custom_character_values`) not being updated.
The change event message was generated but the `character` instance was not actually updated.
=> Fixed character stats not updated as conversation continues

src/games/fallout4.py, src/games/skyrim.py
Remove the audio files copy for Fallout 4 in fallout4.py. The wav files are not used anymore since FO4 caches audio in a way that prevent wav file substitutions while the game is running. The wav files also cause crashes when trying to load new NPCs that are absent from the voide model list. 
Add an additional try block in prepare_sentence_for_game() for Fallout 4 that attempts creates a missing subdirectory for the voice file in the Mantella.esp directory if it's absent for some reason. 
Fix the FEMALE_VOICE_MODELS & MALE_VOICE_MODELS lookup functions so that they correctly append "Race" at the end of the search string for both Fallout4.py & Skyrim.py 
Fix the if condition check for actor_race in prepare_sentence_for_game() for Skyrim and Fallout to correctly compared to an integer …
=> Misc fixes : NPC lookup and audio files copy

src/config/config_loader.py, src/config/definitions/vision_definitions.py, src/config/mantella_config_value_definitions_new.py, src/image/image_manager.py, src/llm/openai_client.py
Removed the UI option to resize / not resize captured images in favour of following the resolution guidelines outlined here:
https://platform.openai.com/docs/guides/vision/managing-images
=> Replaced resize image option with low resolution mode

data/Skyrim/skyrim_weather.csv, src/character_manager.py, src/config/config_file_writer.py, src/conversation/context.py, src/conversation/conversation.py, src/games/skyrim.py, src/output_manager.py, src/tts/piper.py, src/tts/synthesization_options.py, src/tts/ttsable.py, src/tts/xtts.py, src/tts/xvasynth.py, src/utils.py
- If an NPC is dismissed from a conversation, a summary is created and every NPC including the dismissed one will get it
- fixed potential type error with `APIConnectionError` in `output_manager.py`
- fixed typo on `skyrim.py` that caused the weather classification to crash when the weather ID was unknown.
- added class `SynthesizationOptions` in `synthesization_options.py`.
- simple data holding class for additional information that can influence the synthesization of a voice line
- contains the `aggro` information now that was missing after the tts rework
- is passed to `ttsable.tts_synthesize` in place of the old aggro bool
- fixed typo that caused the start of the xVASynth server from MantellaSoftware to fail
- attempted fix of the `samplerate` error #335 by wrapping it into a …
=> Fixed summary when dismissing NPCs, several smaller TTS issues and more

src/llm/openai_client.py
This wraps `openai_client.streaming_call()` and `openai_client.request_call()` to be behind the same lock, blocking any of them being called while a call to either of them is still ongoing.
The fix is potential because:
- I wasn't able to find the exact reason why calls to `openai_client.streaming_call()` didn't resturn any result.
- I simply assumed that there is a possibility that both can be called in parallel.
- Since this was implemented I didn't get another block in my tests, but because of the randomness of this, I can't be sure.
- Having more locks has the potential of unwanted deadlocks, but I didn't encounter any.
=> Potential fix for non responsive LLM after summary

src/config/config_loader.py, src/config/definitions/other_definitions.py, src/config/mantella_config_value_definitions_new.py, src/conversation/conversation.py, src/game_manager.py, src/llm/message_thread.py
- Added `max_count_events` config value, default 5
- Only the last `max_count_events` events are added to a player message
- Changed reload of conversation to only add as many last messages back as their token count doesn't exceed 10% of context size
=> Added max count events, changed reload to use token count

src/conversation/context.py, src/conversation/conversation.py, src/game_manager.py
- Set location variable as optional to accommodate https://github.com/art-from-the-machine/Mantella-Spell/pull/73
- Context is no longer updated for each voiceline delivered, and is instead only updated when the player speaks
=> Actor and context data caching

src/config/config_loader.py, src/config/definitions/language_definitions.py, src/config/mantella_config_value_definitions_classic.py, src/config/mantella_config_value_definitions_new.py, src/game_manager.py, src/http/communication_constants.py, src/output_manager.py
Added NPC action to open their inventory to give / take items.
=> Added inventory action

src/tts/xtts.py
A list of available XTTS models can be pulled by querying the service. Previously, this list was referenced against the `voice_model` and `advanced_model` columns of the selected game's character CSV and filtered based on models present in this CSV. This filter has been removed to allow players to select models not contained in the game's CSV.
=> Remove filtering of XTTS models list by CSV contents

src/ui/settings_ui_constructor.py
An update to a config value is only made if the new value is different from the old value
=> Fixed ghost updates from UI

src/ui/settings_ui_constructor.py
Min-max bounds are now handled by our own config value constraints.
=> Fix gradio min-max bounds for int and float causing exceptions

data/actions/follow.json, data/actions/inventory.json, data/actions/offend_forgive.json, src/config/config_file_writer.py, src/config/config_json_writer.py, src/config/config_loader.py, src/config/config_values.py, src/config/definitions/language_definitions.py, src/config/definitions/other_definitions.py, src/config/definitions/prompt_definitions.py, src/config/mantella_config_value_definitions_new.py, src/config/types/config_value_multi_selection.py, src/config/types/config_value_visitor.py, src/conversation/action.py, src/conversation/context.py, src/conversation/conversation.py, src/conversation/conversation_type.py, src/game_manager.py, src/output_manager.py, src/ui/settings_ui_constructor.py
- moves the definition of actions to JSON files located in `.\data\actions`
- adding a new action is now as simple as adding a new JSON file to the folder which can also be done by mods
- actions are now dynamically inserted into the prompts using the new `{actions}` variable and respect the language override
- adds multi-select config values that support `list[str]`. Both for loading from and saving to the `config.ini` as well as displaying them in the UI
- add `active_actions` config value that allows a user to turn actions on and off
- language override config values for the keywords of actions are generated automatically
@art-from-the-machine 
I was not able to trigger the inventory action in any way although I see a clear `mantella_npc_inventory` action going out as part of a …
=> Added customizable actions

src/output_manager.py
- Fixed voice change function call for multi NPC conversations
- Adjusted LLM timing logging to more accurately present response times
- Added runtime logging for various functions
=> Fixed voice change function call for multi NPC conversations

src/http/communication_constants.py, src/http/routes/mantella_route.py
Added an "initialization" request to force `_setup_route()` to trigger. This allows the server to pre-prepare for a conversation rather than this process only being triggered when a conversation is started (and adding unnecessary run time).
See here for the Mantella Spell implementation of this request type: https://github.com/art-from-the-machine/Mantella-Spell/pull/104
=> Added Mantella request to force settings to initialize

src/config/config_loader.py, src/config/definitions/other_definitions.py, src/config/mantella_config_value_definitions_new.py, src/conversation/conversation.py, src/game_manager.py
Added timer to decide whether or not in-game events need to be updated once the player has spoken.
When an NPC is finished speaking, the latest in-game events are passed to the Mantella window. However, the player doesn't always respond immediately, so if `events_refresh_time` has passed, a request to update events will be passed to the game before passing the player's input and events to the LLM.
=> Added in game events refresh timer

src/config/config_loader.py, src/tts/ttsable.py
If the Creation Kit is installed, the Creation Kit files will be installed in the flat versions of Fallout and Skyrim. To work around this, Mantella will check if it can find the flat version of the game in the same folder as the VR version.
=> Path fix for VR LipGen folders

src/game_manager.py, src/llm/output/change_character_parser.py
Removed code to change voice models before the TTS synthesizer is ready to senthesize the given line
=> Remove early voice model changing

src/config/definitions/llm_definitions.py, src/config/definitions/vision_definitions.py
The recommended temperature setting can change from one LLM to another. Because of this, the default temperature setting of 1.0 has been removed on the Mantella side, allowing the LLM service to choose the appropriate default temperature.
=> Remove temperature from default LLM settings

requirements.txt, src/config/config_loader.py, src/config/definitions/stt_definitions.py, src/config/mantella_config_value_definitions_new.py, src/stt.py
- Added ability to load Moonshine model from local folder
- This folder is automatically set when Mantella.exe is run by the launcher
- Otherwise, the folder can be manually set in the `Speech-to-Text`->`Moonshine Folder` setting in the UI. If set this way, this setting must point to a `moonshine` folder which contains two subfolders: `model name` and `model precision` (eg `/tiny/quantized/files.onnx`)
- Updated Moonshine version to take advantage of quantized models
=> Add local moonshine model

src/config/config_loader.py, src/config/config_values.py, src/config/definitions/llm_definitions.py, src/config/mantella_config_value_definitions_new.py, src/config/types/config_value_multi_selection.py, src/config/types/config_value_selection.py, src/conversation/conversation.py, src/conversation/conversation_type.py, src/game_manager.py, src/llm/image_client.py, src/llm/message_thread.py, src/llm/messages.py, src/llm/output/narration_parser.py, src/output_manager.py, src/remember/summaries.py
Added config values for LLM output parsing:
- `narration_start_indicators`
- `narration_end_indicators`
- `speech_start_indicators`
- `speech_end_indicators`
- `narration_indicators`
- fourth option for `narration_handling` -> Ignore narration changes entirely. Everything is speech.
Added `corresponding_enums` parameter to `ConfigValueSelection`. This allows to directly work with enums instead of the strings within the software. Saving and loading is still done using strings.
Fixed bug in `ConfigValueMultiSelection` that would not load empty strings as values from the `config.ini`. These are now treated as empty lists.
=> Added config values for LLM output parsing

src/tts/ttsable.py
Changed error message to indicate full path of LipGenerator.exe if not found.
=> Fix: set LipGenerator.exe working directory to temp voiceline path.
