README.md
config.ini
src/config_loader.py
src/tts.py

If the first Web Request check for xVASynth fails, tries to launch xVASynth as a subprocess. See commit messages for other changes.
resolves #9

Run xVAsynth alongside Mantella; resolves #9

---

config.ini
src/config_loader.py
src/tts.py

Will work with v2 xVASynth models as there is an issue with v3:
https://github.com/DanRuta/xVA-Synth/pull/53

tts: xVASynth pace parameter

---

main.py
src/game_manager.py

Currently doesn't do anything, but it makes certain compatibility patches (that need access to the player dialogue) easier.

Add player subtitle functionality

---

config.ini
main.py
src/character_manager.py
src/config_loader.py
src/game_manager.py
src/output_manager.py
src/setup.py

Read the NPC's in-game voice model and write to this folder

Use default in game voice for NPC

---

config.ini
src/config_loader.py
src/output_manager.py
src/stt.py

Removed subtitles_enabled option as it is now handled in game

Removed subtitles_enabled option

---

src/tts.py

Using Path lib to not confuse users with differing slash directions on Windows.
An alternative way to lessen impact of #46

tts: File Not Found verbose

---

main.py
src/character_manager.py
src/config_editor.py
src/config_loader.py
src/game_manager.py
src/tts.py

Open most files with encoding UTF-8

---

config.ini
src/config_loader.py
src/output_manager.py

Made the wait for voiceline buffer a configurable option

Added wait buffer as configurable option

---

README.md

Also added Skyrim to Required/Optional section titles as people keep adding Mantella Software and xVASynth as a mod to Skyrim.

README.md: Whisper section + CUDA paragraph

---

config.ini
src/config_loader.py
src/stt.py

Few had requested this and I did not know that the feature is included in OpenAI's Whisper STT.

Whisper: config option to auto translate spoken text to English

---

src/game_manager.py

Otherwise it fully hogs a CPU core while Mantella is supposedly idle.

game_manager.py: decreases stress on CPU core due to load_data

---

src/character_manager.py
src/game_manager.py
src/output_manager.py
src/tts.py

Does nothing on the TTS side without an update to v3.0.3 of xVASynth.

tts: send default minimum anger emotion when in combat

---

main.py
src/character_manager.py
src/game_manager.py
src/output_manager.py

Checks whether the NPC in a one-on-one conversation is in combat once every response generation to change the voice tone to angry

Added text file to check for combat and change xVASynth tone

---

main.py
src/game_manager.py

Fixes debug mode, it wasn't writing some files in skyrim dir correctly.
The debugging character's info is now read from CSV and correct voice model is set. If not found in CSV, male/female and race is randomized.

Debug mode fix

---

config.ini
src/config_loader.py
src/output_manager.py

NPC actions have been moved to the MCM

Remove experimental flag from config

---

.gitignore
src/character_manager.py
src/config_loader.py
src/setup.py
src/tts.py
src/utils.py

Added handling of exe to work with relative paths if run externally (ie working directory is not the exe directory)

Dynamic exe handling of relative folders

---

config.ini
src/config_loader.py
src/output_manager.py

added multi sentence processing inside output_manager with the use of a number of words minimum to create a sentence :
;Minimum number of words per sentence sent to the TTS
;If you encounter audio artifacts at the end of sentences, try increasing this number.
;Be aware, the higher the number, the longer the TTS audio processing time might take
number_words_tts = 10

multi sentence xtts

---

config.ini
src/config_loader.py
src/tts.py

Condensed XTTS URLs to a single URL for players switching between local / external XTTS servers. Configured XTTS audio response to send the audio file directly instead of saving to a folder.

Simplified connection to external XTTS

---

src/output_manager.py

This new implementation fixes https://github.com/art-from-the-machine/Mantella/issues/143

Added back asterisks filtering in LLM response

---

src/tts.py

Fixes https://github.com/art-from-the-machine/Mantella/issues/144

Reconnect to xVASynth if connection lost

---

main.py

Fixes https://github.com/art-from-the-machine/Mantella/issues/147 and https://github.com/art-from-the-machine/Mantella/issues/159

Fixed missing end_conversation file bug

---

src/character_manager.py

Solves https://github.com/art-from-the-machine/Mantella/issues/150

Conversation logs do not get saved for generic NPCs

---

src/tts.py

Fixes https://github.com/art-from-the-machine/Mantella/issues/155

Fixed FaceFXWrapper call to dynamically use Skyrim or Fallout 4

---

src/stt.py

Implemented @teddybear082's PR to remove the need to save an audio file called player_recording.wav.
Fixes https://github.com/art-from-the-machine/Mantella/issues/128

Removed need for player recording wav

---

config.ini
src/output_manager.py

Fixes https://github.com/art-from-the-machine/Mantella/issues/169

Fixed max_response_sentences

---

src/config_loader.py
src/setup.py

Fixes https://github.com/art-from-the-machine/Mantella/issues/82

Error handling messages for config.ini and CSV files

---

src/conversation/conversation.py

Fixes https://github.com/art-from-the-machine/Mantella/issues/170

Starting prompt change to accommodate more than two NPCs

---

src/conversation/conversation.py
src/remember/summaries.py

Fixes https://github.com/art-from-the-machine/Mantella/issues/185

Collecting thoughts response from correct NPC

---

config.ini
src/config_loader.py
src/tts.py

Addresses https://github.com/art-from-the-machine/Mantella/issues/158

Reshuffled config file

---

src/tts.py

Fixes https://github.com/art-from-the-machine/Mantella/issues/195

Voicelines no longer save to individual NPC folder

---

config.ini

Fixes https://github.com/art-from-the-machine/Mantella/issues/174

Edited folder paths for uniformity

---

config.ini
src/config_loader.py

Many settings have been shuffled around which has broken the formatting of the config editor. This editor needs to be reworked to accommodate .Advanced settings in the next release

Hidden config editor temporarily for v0.11

---

config.ini

Change for the description of these line to include "xtts-api-server-mantella.exe"

Update config.ini for the line xtts_server_folder

---

src/output_manager.py

Fixes https://github.com/art-from-the-machine/Mantella/issues/210

Prevent Mantella from crashing when _mantella_audio_ready.txt cannot be accessed

---

src/tts.py

change to change voice so it doesn't try to change model at each speaker change, the feature is still there

tts.py change voice update

---

config.ini
main.py
src/remember/summaries.py

Fixes https://github.com/art-from-the-machine/Mantella/issues/221

Added game to memory prompts

---

src/config_loader.py

Fixes https://github.com/art-from-the-machine/Mantella/issues/219

Added warning when default game in config has not been edited

---

src/llm/openai_client.py
src/output_manager.py

Fixes https://github.com/art-from-the-machine/Mantella/issues/218

Added better error messages for invalid API keys

---

docs/pages/installation_fallout4.md

A new torrent was created that does not have the voice models archived as this new torrent increases the incentive to keep the files and seed them to peers.

Update installation_fallout4.md: new Torrent magnet

---

src/output_manager.py

Previously, LLM actions were stripped from the final response once parsed. This means that an LLM would be unable to see the actions it has taken / characters it has spoken as from previous messages.

Save LLM actions to conversation messages

---

config.ini
src/llm/openai_client.py
src/output_manager.py

Fixes https://github.com/art-from-the-machine/Mantella/issues/225

Max response multi-NPC override

---

src/tts.py

- Stopped voice variable from incorrectly being overriden by an incorrect value
- Added back check to ensure Fallout 4 versions of MaleEvenToned / FemaleEvenToned are called correctly

Fixed voice changing

---

src/config/config_loader.py
src/config/definitions/game_definitions.py
src/config/definitions/language_definitions.py
src/config/definitions/llm_definitions.py
src/config/definitions/other_definitions.py
src/config/definitions/prompt_definitions.py
src/config/definitions/stt_definitions.py
src/config/definitions/tts_definitions.py
src/config/mantella_config_value_definitions_classic.py
src/config/mantella_config_value_definitions_new.py
src/games/gameable.py
src/http/routes/mantella_route.py
src/llm/openai_client.py
src/setup.py
src/stt.py
src/tts.py
src/ui/settings_ui_constructor.py
src/ui/start_ui.py

Added a setting to change whether the Mantella UI auto launches on each run. Updated UI descriptions and unused tabs.

Auto launch UI setting and UI description updates

---

src/color_formatter.py
src/conversation/conversation.py
src/game_manager.py
src/output_manager.py
src/setup.py
src/tts.py

Also fixed a couple of type issues that showed up as errors using my type settings.

Fixed XTTS synthesize call not working

---

src/color_formatter.py
src/config/config_loader.py
src/config/definitions/other_definitions.py
src/config/mantella_config_value_definitions_new.py
src/conversation/conversation.py
src/game_manager.py
src/games/fallout4.py
src/games/skyrim.py
src/output_manager.py
src/setup.py
src/tts.py

This can be used for improved immersion or to fill the gap between player input and LLM response.

Added option to voice the player input by TTS

---

src/remember/summaries.py

- Splits loaded summaries into paragraphs
- Adds duplicate paragraphs only once to the prompt

Add duplicate summary paragraphs only once

---

src/setup.py

This works for me as it worked before and is supposed to also respect changes in the user home directory.
Attempt to fix #337

Respect Windows settings for user directory

---

src/stt.py

Fixes https://github.com/art-from-the-machine/Mantella/issues/325

Added extra lines to Whisper ignore list

---

src/output_manager.py
src/tts/piper.py

Fixes https://github.com/art-from-the-machine/Mantella/issues/328

Short sentence synthesis fix

---

src/tts/piper.py

Fixes https://github.com/art-from-the-machine/Mantella/issues/324

Search for Piper voice model in each CSV column

---

src/games/fallout4.py
src/games/skyrim.py

Added NPC sex and race to generic NPC bios.

Added more detailed bios for generic NPCs

---

src/character_manager.py
src/conversation/conversation.py
src/conversation/conversation_log.py
src/game_manager.py
src/games/fallout4.py
src/games/gameable.py
src/games/skyrim.py
src/http/communication_constants.py
src/remember/summaries.py

to receive both ids from https://github.com/art-from-the-machine/Mantella-Spell/pull/86

Added both baseID and refID and made their usage throughout software explicit

---

src/game_manager.py
src/http/communication_constants.py

Fixes https://github.com/art-from-the-machine/Mantella/issues/220

Detect and process NPC action commands

---

src/conversation/context.py

Added warning messages to the prompt construction in case bios or summaries get removed

Add prompt length math logging

---

main.py
requirements.txt
src/config/definitions/stt_definitions.py
src/http/routes/stt_route.py
src/stt.py

- When searching for an API key in the speech-to-text class, the code now first searches for a file called `STT_SECRET_KEY.txt` before searching for `GPT_SECRET_KEY.txt`
- New Whisper models have been added as options in the Mantella UI

Add STT secret key file

---

.gitignore
main.py
src/config/config_loader.py
src/config/definitions/stt_definitions.py
src/config/mantella_config_value_definitions_new.py
src/conversation/context.py
src/conversation/conversation.py
src/game_manager.py
src/http/communication_constants.py
src/http/routes/mantella_route.py
src/http/routes/stt_route.py
src/output_manager.py
src/stt.py
src/tts/ttsable.py

- Added seperate secret key file (`STT_SECRET_KEY.txt`) option to connect to speech-to-text services. If no `STT_SECRET_KEY.txt` file is present, the `GPT_SECRET_KEY.txt` file is used instead.
- Added ability to connect to non-OpenAI speech-to-text services (that have a OpenAI endpoint compatability)
- Character names are now passed as context to Whisper from the Python side instead of the Papyrus side
- Added threading to STT code to allow for player mic input at any time
- Added checks throughout the code to see if the player is interrupting via the mic
- STT route is no longer needed

Speech-to-text improvements

---

requirements.txt
src/config/config_loader.py
src/config/definitions/stt_definitions.py
src/config/mantella_config_value_definitions_new.py
src/conversation/conversation.py
src/stt.py
src/tts/piper.py

- Switched from the `speech_recognition` library to `silero_vad` for improved speech detection and performance
- Added functionality to periodically transcribe mic audio instead of waiting for `pause_threshold` to be reached

Speech-to-Text Rework

---

src/config/config_loader.py
src/config/definitions/other_definitions.py
src/config/mantella_config_value_definitions_new.py
src/games/fallout4.py
src/games/gameable.py
src/games/skyrim.py

Add option to save files to original voice folder for players who experience issues with Papyrus failing to change the voice folder of NPCs to MantellaVoice00

Add option to save files to original voice folder

---

src/config/config_loader.py
src/config/mantella_config_value_definitions_new.py
src/llm/client_base.py
src/llm/image_client.py
src/llm/llm_client.py

Remove LLM Priority setting from the Mantella UI for OpenRouter models. The implementation of this is quite basic, so it is better to recommend players configure this setting in OpenRouter's own preferences page: https://openrouter.ai/settings/preferences

Remove LLM Priority setting

---

src/stt.py

Fixed a bug where multiple empty interim transcriptions in a row cause the exe to lag

Fix interim transcriptions from getting out of hand
